FROM ubuntu:22.04
WORKDIR /usr/src/app

ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONBUFFERED=1

# install dependencies
RUN apt-get update -y && apt-get install -y --no-install-recommends gcc

# install pip
RUN apt-get update && apt-get install -y python3 python3-pip

# lint
RUN pip install --upgrade pip
COPY . /usr/src/app/
RUN pip install --upgrade pip setuptools wheel

COPY requirements.txt .
RUN pip wheel --no-cache-dir --no-deps --wheel-dir /usr/src/app/wheels -r requirements.txt
RUN chmod -R 777 /usr/src/app/
