name: Django Docker Tests

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
  workflow_dispatch:

jobs:
  test_django_docker:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: First Stage Build Docker image with Dockerfile-prod-builder
        working-directory: ./app
        run: docker build -t django-recomm-july-build -f Dockerfile-prod-builder .
       
      - name: List Docker images
        run: docker images 
        
      - name: Run container and execute tests
        run: |
          docker run --name test-image django-recomm-july-build tail -f /dev/null
          docker exec -it test-image sh -c '[ "$(pwd)/" = "/usr/src/app/" ] && echo true || echo false'
          docker exec -it test-image sh -c '[ "$PYTHONDONTWRITEBYTECODE" = "1" ] && [ "$PYTHONBUFFERED" = "1" ] && echo true || echo false'
          docker exec -it test-image sh -c '[ -d wheels ] && [ ! -f wheels/requirements.txt ] && echo true || echo false'
          docker rm -f test-image
          
   
      

